name: Tests

on: [push]

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install Composer dependencies
        run: composer install -q --no-ansi --no-interaction --no-suggest --no-progress --prefer-dist

      - name: Cache Composer dependencies
        uses: actions/cache@v1
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}

      - name: Copy dotenv file and generate app key
        run: |
          php -r "file_exists('.env') || copy('.env.ci', '.env');"
          php artisan key:generate --no-interaction --force
          php artisan jwt:secret --no-interaction --force

      - name: Migrate schemas and run tests
        run: |
          mkdir -p database
          touch database/database.sqlite
          php artisan migrator --no-interaction --force
          php artisan test --without-tty

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: ozana_test
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
